language: python
python:
  - "2.7"
addons:
  postgresql: "9.3"
env:
  global:
    - PIP_DOWNLOAD_CACHE=$HOME/.pip_cache
    - DATABASE_URL='postgres://travis@localhost/se_tags')
  matrix:
    - TOX_ENV=py27-dj17
    - TOX_ENV=flake8
cache:
  directories:
    - $HOME/.pip-cache/
before_install:
  - sudo apt-get update -qq
  #- sudo apt-get install -qq libatlas-dev libatlas-base-dev liblapack-dev gfortran
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda/bin:$PATH
  - conda update --yes conda
  - travis_retry conda install --yes python=$TRAVIS_PYTHON_VERSION pip numpy scipy
install:
  - "travis_retry conda install tox"
before_script:
  - psql -c 'create database mozy;' -U postgres
script:
  - tox -e $TOX_ENV
after_script:
  - cat .tox/$TOX_ENV/log/*.log
