sudo: false
language: python
python:
  - "2.7"
addons:
  postgresql: "9.3"
env:
  matrix:
    - TOX_ENV=py27-dj17
    - TOX_ENV=flake8
cache: pip
before_install:
  - pip install conda
  - conda init
  - conda create -p $HOME/py --yes ctox pip numpy scipy "python=$TRAVIS_PYTHON_VERSION"
  - export PATH=$HOME/py/bin:$PATH
install:
  - ctox --version
before_script:
  - psql -c 'create database mozy;' -U postgres
script:
  - ctox -e $TOX_ENV
after_script:
  - cat .tox/$TOX_ENV/log/*.log
