sudo: false
language: python
python:
  - "2.7"
addons:
  postgresql: "9.3"
env:
  matrix:
    - TOX_ENV=py27-dj17
    - TOX_ENV=flake8
cache: pip
before_install:
  - pip install conda
  - conda init
  - conda update --yes conda
  - conda install --yes -n python=$TRAVIS_PYTHON_VERSION condaenv pip
  - conda create --yes -n condaenv python=$TRAVIS_PYTHON_VERSION
  - source activate condaenv
install:
  - travis_retry pip install tox
before_script:
  - psql -c 'create database mozy;' -U postgres
script:
  - tox -e $TOX_ENV
after_script:
  - cat .tox/$TOX_ENV/log/*.log
